from nutikacompile import compile_with_nuitka

wholecommand = compile_with_nuitka(
    pyfile=r'C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\main.py',
    icon=r'C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\icon\Logo.ico',
    disable_console=True,
    file_version='1.0.0.0',
    onefile=True,
    outputdir='c:\\FullBusiness',
    addfiles=[
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\imports.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\funcoes.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\LancFinanceiro.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\main.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\Usr.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrAlterar_Senha.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrAnexos.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrAprovacaoLctos.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrBaixasFinanceiras.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrBorderoBancario.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrCadastro_Curvas_Negocio.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrCadastros.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrCalcular_Orcamento.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrContas_Pagar.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrCronograma_Hierarquico.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrCronograma.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrExtratoBancario.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrExtratosClientes_Fornecedores.py",    
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrModulos_Sistema.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrPermissoes_Sistema.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrPesquisaMercado.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrPremissas.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrRelatorio_EstudosNegocio.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrRelatorio_Fluxo_Projetado.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrRelatorio_Orcamento.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrRelatorio_Premissas.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrSimulador_Maps.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrSimulador_rel.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrSites.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrTelaPrincipal.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\UsrUsuarios_Sistema.py",  
        r"C:\Users\Clayton\OneDrive - URBANVIX URBANIZADORA E INCORPORADORA LTDA\Documentos\GitHub\fullhouse-Business\widgets.py",  
    ],
    delete_onefile_temp=False, 
    needs_admin=True,
    arguments2add='--msvc=14.3 --noinclude-numba-mode=nofollow --jobs=1',
)